# Generated by Django 4.1.1 on 2023-02-19 09:42

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('treeemps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treeemps.subs')),
            ],
        ),
    ]
