# Generated by Django 4.1.1 on 2023-02-19 09:53

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('empls', '0020_alter_employee_position_and_more'),
        ('treeemps', '0002_emps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='empls.employee'),
        ),
        migrations.DeleteModel(
            name='Emps',
        ),
    ]
