# Generated by Django 4.1.1 on 2023-02-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeemps', '0004_emps_alter_subs_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emps',
            name='level',
        ),
        migrations.RemoveField(
            model_name='emps',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='emps',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='emps',
            name='tree_id',
        ),
    ]
