# Generated by Django 4.1.1 on 2023-02-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treeemps', '0005_remove_emps_level_remove_emps_lft_remove_emps_rght_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emps',
            old_name='dir',
            new_name='direct',
        ),
    ]
