# Generated by Django 4.1.1 on 2023-02-19 10:21

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('treeemps', '0007_alter_subs_name_alter_subs_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subs',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, choices=[('Иван Иванович', 'Иван Иванович'), ('Мария', 'Мария'), ('Олег', 'Олег'), ('Владимир', 'Владимир'), ('Наталья', 'Наталья'), ('Анна', 'Анна')], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='treeemps.subs'),
        ),
    ]
