# Generated by Django 4.1.1 on 2023-02-19 10:37

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('treeemps', '0008_alter_subs_name_alter_subs_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='name',
            field=models.CharField(choices=[('Иван Иванович', 'Иван Иванович'), ('Мария', 'Мария'), ('Олег', 'Олег'), ('Сергей', 'Сергей'), ('Ольга', 'Ольга'), ('Марина', 'Марина'), ('Владимир', 'Владимир'), ('Наталья', 'Наталья'), ('Илья', 'Илья'), ('Анна', 'Анна'), ('Света', 'Света'), ('Евгений', 'Евгений'), ('Оксана', 'Оксана'), ('Антон', 'Антон'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subs',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='treeemps.subs'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Иван Иванович', 'Иван Иванович'), ('Мария', 'Мария'), ('Олег', 'Олег'), ('Сергей', 'Сергей'), ('Ольга', 'Ольга'), ('Марина', 'Марина'), ('Владимир', 'Владимир'), ('Наталья', 'Наталья'), ('Илья', 'Илья'), ('Анна', 'Анна'), ('Света', 'Света'), ('Евгений', 'Евгений'), ('Оксана', 'Оксана'), ('Антон', 'Антон'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=50)),
                ('direct', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treeemps.subs')),
            ],
        ),
    ]
