# Generated by Django 4.1.1 on 2023-01-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('date_coming', models.DateField(verbose_name='Дата приема')),
                ('cash', models.PositiveSmallIntegerField(default=0, verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
