# Generated by Django 4.1.1 on 2023-01-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empls', '0004_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='director',
            field=models.CharField(blank=True, choices=[('младший сотрудник', 'младший сотрудник')], max_length=50, null=True, verbose_name='Начальник'),
        ),
    ]
