# Generated by Django 4.1.1 on 2023-01-19 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empls', '0005_alter_employee_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empls.employee', verbose_name='Начальник'),
        ),
    ]
