# Generated by Django 4.1.1 on 2023-01-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empls', '0008_position_rank_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('младший сотрудник', 'младший сотрудник'), ('сотрудник', 'сотрудник'), ('старший сотрудник', 'старший сотрудник'), ('помощник главного', 'помощник главного'), ('главный', 'главный')], max_length=20, verbose_name='Должность'),
        ),
    ]
