# Generated by Django 4.1.1 on 2023-01-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empls', '0009_alter_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО')),
                ('position', models.CharField(choices=[('главный', 'главный'), ('помощник главного', 'помощник главного'), ('старший сотрудник', 'старший сотрудник'), ('сотрудник', 'сотрудник'), ('младший сотрудник', 'младший сотрудник')], max_length=20, verbose_name='Должность')),
                ('date_coming_b', models.DateField(verbose_name='Дата приема от')),
                ('date_coming_e', models.DateField(verbose_name='Дата приема до')),
                ('cash_min', models.PositiveSmallIntegerField(default=0, verbose_name='Зарплата от')),
                ('cash_max', models.PositiveSmallIntegerField(default=1000000, verbose_name='Зарплата до')),
            ],
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['rank'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('главный', 'главный'), ('помощник главного', 'помощник главного'), ('старший сотрудник', 'старший сотрудник'), ('сотрудник', 'сотрудник'), ('младший сотрудник', 'младший сотрудник')], max_length=20, verbose_name='Должность'),
        ),
    ]
