# Generated by Django 4.1.1 on 2023-01-22 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empls', '0010_employeesearch_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesearch',
            name='date_coming_b',
            field=models.DateField(default=datetime.date(2014, 1, 1), verbose_name='Дата приема от'),
        ),
        migrations.AlterField(
            model_name='employeesearch',
            name='position',
            field=models.CharField(blank=True, choices=[('главный', 'главный'), ('помощник главного', 'помощник главного'), ('старший сотрудник', 'старший сотрудник'), ('сотрудник', 'сотрудник'), ('младший сотрудник', 'младший сотрудник')], max_length=20, null=True, verbose_name='Должность'),
        ),
    ]
