# Generated by Django 4.1.1 on 2023-01-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empls', '0012_alter_employeesearch_date_coming_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_coming',
            field=models.DateTimeField(verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='employeesearch',
            name='date_coming_b',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeesearch',
            name='date_coming_e',
            field=models.DateTimeField(),
        ),
    ]
