# Generated by Django 4.1.1 on 2023-01-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empls', '0014_alter_employee_date_coming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_coming',
            field=models.DateField(auto_now_add=True, verbose_name='Дата приема'),
        ),
        migrations.AlterField(
            model_name='employeesearch',
            name='date_coming_b',
            field=models.DateField(),
        ),
    ]
