# Generated by Django 4.1.1 on 2023-01-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empls', '0015_employee_image_alter_employee_date_coming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
