# Generated by Django 4.1.1 on 2023-02-01 07:19

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('empls', '0017_alter_employee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('position', models.CharField(choices=[('главный', 'главный'), ('помощник главного', 'помощник главного'), ('старший сотрудник', 'старший сотрудник'), ('сотрудник', 'сотрудник'), ('младший сотрудник', 'младший сотрудник')], max_length=20, verbose_name='Должность')),
                ('date_coming', models.DateField(auto_now_add=True, verbose_name='Дата приема')),
                ('cash', models.PositiveSmallIntegerField(default=0, verbose_name='Зарплата')),
                ('is_director', models.BooleanField(default=False, verbose_name='Есть подчиненные')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics/')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('director', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empls.employeetree', verbose_name='Начальник')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
