# Generated by Django 4.1.1 on 2023-02-20 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empls', '0020_alter_employee_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetree',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники_Tree'},
        ),
    ]
